### ISSUE TITLE
Add Plugins

### ISSUE THREAD

**Issue by morpheuslord** [aserowy/neocode#5]
Where can i edit plugins to add or modify plugins

**Comment by aserowy** [comment]
[nvim.lua](https://github.com/aserowy/neocode/blob/main/lua/nvim.lua)
Here are alle plugins and inits for the nvim instance launched in shell.

[vscode.lua](https://github.com/aserowy/neocode/blob/main/lua/vscode.lua)
Here lies the init with plugin management for vscode instances.

**Comment by morpheuslord** [comment]
thanks man

**Comment by morpheuslord** [comment]
I had another issue :
![nvim @ LAPTOP-V17Q7F9M 09-11-2022 23_13_03](https://user-images.githubusercontent.com/70637311/200902343-7b017a4a-57fc-401d-a82e-72692991f852.png)
What should I do about this?

**Comment by aserowy** [comment]
hmmm, i have no idea :D I am using my config on win, wsl2 and nixos without ever running into this message.

**Comment by morpheuslord** [comment]
no idea i guess it might be with language support maybe but no clue

**Comment by aserowy** [comment]
@morpheuslord, on a brand new machine i could replicate the behavior! I installed llvm only and building started failing. After replacing llvm with gcc (installed with scoop) compiling ran fine!

Hope this helps :D

**Comment by morpheuslord** [comment]
I guess using it with Linux is the best possible answer cause whatever I do on windows it wont work
