### ISSUE TITLE
Change the keybindings to decrease window size

### ISSUE THREAD

**Issue by siyuanwu99** [aserowy/neocode#6]
Hello,

I would like to use <kbd>alt + h</kbd> to switch from different buffers but it's occupied.
I wonder how can I disable <kbd>alt + h</kbd> to increase/decrease window size?

**Comment by aserowy** [comment]
Heho,

the window bindings are set with https://github.com/aserowy/tmux.nvim (currently the default setting). To overwrite those, use the documentation of this plugin:

https://github.com/aserowy/tmux.nvim#navigation

Kind regards
Alexander

**Comment by siyuanwu99** [comment]
Thanks for your kind replies!
